name: sample-action
on: 
  pull_request:
    types: 
      - opened
  workflow_dispatch:
env:
  name: ${{ secrets.name }}
jobs:

  test:
    runs-on: ubuntu-latest
    container:
      image: node:16
    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb
      MONGODB_CLUSER_ADDRESS: mongodb
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: admin
    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
    steps:
      - name: Get-code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: verify connection
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Build tests
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: package.json
  download-artifact:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download-artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: list-artifacts
        run: ls
      - name: using env
        run: echo "the name of the env is ${{ env.name }}"
        
        
