name: use-reuse-worflow
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: actions/checkout@v3
      - name: using reuse
        uses: ./.github/workflow/reuse.yaml
